# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: espesd99
# "service" is the name of this project. This will also be added to your AWS resource names.
service: BooksTableNew

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource:
        - "arn:aws:dynamodb:us-east-1:536697266402:table/BooksTableNew"

resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BookTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: BookID
            AttributeType: S
        KeySchema:
          - AttributeName: BookID
            KeyType: HASH


functions:
  createBook:
    handler: src/createBook.createBook
    events:
      - httpApi:
          path: /books
          method: post

  getBooks:
    handler: src/getBooks.getBooks
    events:
      - httpApi:
          path: /books
          method: get

  getBookById:
    handler: src/getBook.getBookById
    events:
      - httpApi:
          path: /books/{bookId}
          method: get

  updateBook:
    handler: src/updateBook.updateBook
    events:
      - httpApi:
          path: /books/{BookID}
          method: put

  deleteBook:
    handler: src/deleteBook.deleteBook
    events:
      - httpApi:
          path: /books/{BookID}
          method: delete


 